- become: yes
  hosts: all
  name: Setup and
  tasks:
    - name: Get ECR Login
      shell: aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com
      register: ecr_login
    - name: Pull Estuary from ECR
      community.docker_image:
        name: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ app }}-ecr:latest"
        source: pull
        force_source: yes
        force: yes
        state: present
        timeout: 300
      register: estuary_image_pull
    - name: Install the Rexray Docker Plugin
      community.docker_plugin:
        name: rexray/ebs
        alias: rexray/ebs
        state: present
        timeout: 300
      register: rexray_plugin_install
    - name: Create a Docker Volume for Estuary with Rexray
      community.docker_volume:
        name: { { app } }-volume
        driver: rexray/ebs
        driver_options:
          size: { { ebs_size } }
          volumeType: { { ebs_type } }
        state: present
        timeout: 300
      register: estuary_volume_create
    - name: Run Estuary
      docker_container:
        name: estuary
        image: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ app }}-ecr:latest"
        state: started
        restart_policy: always
        env:
          API_HOSTNAME: "{{ api_hostname }}"
          WWW_HOSTNAME: "{{ www_hostname }}"
          FULLNODE_API: "{{ fullnode_api }}"
          DB_TYPE: "{{ db_type }}"
          DB_ENDPOINT: "{{ db_endpoint }}"
          DB_NAME: "{{ db_name }}"
          VOLUME_DIR: "{{ ebs_mount_dir }}"
        ports:
          - "80:{{ api_port }}"
        volumes:
          - "{{ app }}-volume:{{ ebs_mount_dir }}"
        command: [ "/app/start.sh", "{{ db_username }}", "{{ db_password }}" ]
        register: estuary_container_run

